from graph import build_graph
import streamlit as st
import PyPDF2
import docx


def read_pdf(file):
    reader = PyPDF2.PdfReader(file)
    text = ""

    for page in reader.pages:
        text += page.extract_text() or ""

    return text


def read_docx(file):
    document = docx.Document(file)
    text = ""

    for para in document.paragraphs:
        text += para.text + "\n"

    return text


st.set_page_config(
    page_title="Resume Analyzer",
    page_icon="📄"
)

st.title("📄 Resume Analyzer")

uploaded_file = st.file_uploader(
    label="Upload Resume",
    type=["pdf", "docx"]
)
if uploaded_file is not None and not isinstance(uploaded_file, list):

    if uploaded_file.name.lower().endswith(".pdf"):
        resume_text = read_pdf(uploaded_file)
    else:
        resume_text = read_docx(uploaded_file)

    st.success("🎉 Resume Uploaded Successfully!")


    app_graph = build_graph()


    inputs = {
        "resume_text": resume_text,
        "job_description": ""
    }


    with st.spinner("🤖 AI Agents are analyzing your resume... Please wait..."):
        final_state = app_graph.invoke(inputs)

    st.success("✨ AI Analysis Completed!")
    st.divider()


    tab1, tab2, tab3, tab4 = st.tabs([
        "📄 Resume Raw Text",
        "🧠 AI Agent Analysis",
        "📊 ATS & Job Match",
        "🎯 Interview Questions"
    ])


    with tab1:
        st.subheader("Extracted Text from your Resume")
        st.text_area("Plain Text", resume_text, height=400, label_visibility="collapsed")


    with tab2:
        st.subheader("🧠 Skills & Optimization Report")

        with st.expander("🔍 Basic Profile Analysis", expanded=True):
            st.markdown(final_state.get("analysis", "No data generated by Agent."))

        with st.expander("⚡ Identified Skills & Keywords", expanded=True):
            st.markdown(final_state.get("skills", "No data generated by Agent."))

        with st.expander("💡 Resume Optimization Suggestions", expanded=False):
            st.markdown(final_state.get("suggestions", "No data generated by Agent."))


    with tab3:
        st.subheader("📊 Performance & Match Rating")
        st.markdown(final_state.get("ats", "No data generated by Agent."))
        st.markdown(final_state.get("job_match", "No data generated by Agent."))


    with tab4:
        st.subheader("🎯 Tailored Interview Preparation")
        st.info("Here are some questions customized for your profile by our AI Agent:")
        st.markdown(final_state.get("questions", "No data generated by Agent."))


    st.divider()
    st.download_button(
        label="📥 Download Full AI Analysis Report (TXT)",
        data=final_state.get("final_report", "Empty Report"),
        file_name="Resume_AI_Analysis_Report.txt",
        mime="text/plain"
    )
if uploaded_file is not None and not isinstance(uploaded_file, list):

    if uploaded_file.name.lower().endswith(".pdf"):
        resume_text = read_pdf(uploaded_file)

    else:
        resume_text = read_docx(uploaded_file)

    st.success("Resume Uploaded Successfully")
    st.subheader("Resume Content")

    st.write(resume_text[:1000])